apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: negi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: app1
          image: python:3.9-slim
          command: ["python", "-c", "print('Hello from App1'); import time; time.sleep(3600)"]
