apiVersion: batch/v1
kind: Job
metadata:
  name: app1-job
  namespace: negi
spec:
  completions: 10  # 実行回数（1回実行される）
  parallelism: 2   # 同時に実行するポッド数
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: app1
          image: negis:latest
          imagePullPolicy: Never
          resources:
            limits:
              memory: 128Mi
              cpu: "1"
      restartPolicy: OnFailure  # 失敗した場合に再試行する
