apiVersion: batch/v1
kind: Job
metadata:
  name: my-job1
spec:
  template:
    spec:
      containers:
      - name: my-container1
        image: busybox
        command: ["echo", "Hello, Kubernetes!"]
      restartPolicy: Never
  backoffLimit: 4
