apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  labels:
    app.kubernetes.io/instance: negi-app
  name: test-load-001
  namespace: k6-test-1
spec:
  parallelism: 4
  script:
    configMap:
      name: k6-test
      file: test.js
  runner:
    initContainers:
      - name: init-runner
        image: busybox:latest
        command: ["sh", "-c", "echo 'Initializing before K6 test'"]
    image: negis:latest
    imagePullPolicy: Never
