apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  labels:
    app.kubernetes.io/instance: negi-app
  name: test-load-001
  namespace: k6-test-1
# spec:
#   image: yourusername/custom-k6:latest
#   imagePullPolicy: Never
#   parallelism: 3
#   script:
#     configMap:
#       file: test.js
#       name: k6-script
spec:
  parallelism: 2
  # arguments: --out output-statsd
  runner:
    # xk6 をビルドして作成した Docker イメージを指定.
    image: yourusername/custom-k6:latest
    imagePullPolicy: Never
    # env:
      # ここから環境変数を定義する.
      # K6_STATSD_ADDR では Datadog Agent サービスを指定.
      # - name: K6_STATSD_ADDR
      #   value: "datadog-agent.datadog.svc.cluster.local:8125"
      # # 公式ドキュメントに記載されたものを指定.
      # - name: K6_STATSD_ENABLE_TAGS
      #   value: "true"
      # # Datadog Agent のホストIPを指定.
      # - name: DD_AGENT_HOST
      #   valueFrom:
      #     fieldRef:
      #       fieldPath: status.hostIP
  script:
    configMap:
      file: test.js
      name: k6-script
