apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  namespace: k6-test
  name: test-load-000
spec:
  parallelism: 3
  image: yourusername/custom-k6:latest
  script:
    configMap:
      name: k6-script
      file: test.js
  replicas: 1  
