apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  labels:
    app.kubernetes.io/instance: negi-app
  name: test-load-1000
  namespace: k6-test-1
spec:
  parallelism: 4
  script:
    configMap:
      file: test.js
      name: k6-script
  
  initializer: 
    initContainers:
      - name: init-initializer-log
        image: busybox:latest
        imagePullPolicy: Never
        command: ["sh", "-c", "echo 'is part of initializer pod'"]      

  starter: 
    initContainers:
      - name: init-starter-log
        image: busybox:latest
        imagePullPolicy: Never
        command: ["sh", "-c", "echo 'is part of starter pod'"]      

  runner:
    initContainers:
      - name: init-runner
        image: busybox:latest
        imagePullPolicy: Never
        command: ["sh", "-c", "echo 'Initializing before K6 test'"]

    image: negis:latest
    imagePullPolicy: Never
