apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  labels:
    app.kubernetes.io/instance: negi-app
  name: test-load-001
  namespace: k6-test-1
spec:
  parallelism: 2
  script:
    configMap:
      file: test.js
      name: k6-script
  initializer: 
    initContainers:
      - image: busybox:latest
        command: ["sh", "-c", "echo 'is part of initializer pod'"]
  runner:
    initContainers:
      - image: busybox:latest
        command: ["sh", "-c", "echo 'is part of all 4 testrun pods'"]
    image: negis:latest
    imagePullPolicy: Never
